### ISSUE TITLE
longname.sh

### ISSUE THREAD

**Issue by riverosm** [sisoputnfrba/osada-tests#1]
Buenas, les paso un issue que encontré haciendo uno de los tests:

01234567890123456789.dat

Debería ser

$OSADADIR/01234567890123456789.dat

Saludos

**Comment by sciciliani** [comment]
Si te animás a hacer el push request te lo mergeamos 👍

**Comment by riverosm** [comment]
Buenas, no sé si estoy haciendo algo mal pero no se me habilita la opción el botón para crearlo.

Si intento pushear desde consola en un nuevo branch me da Forbiden.

Saludos!

**Comment by mgarciaisaia** [comment]
¡Gracias por el reporte!

Hace unos días lo corregí en 2d299281b440426f66e88d444b376a7162ef417e

Para editar un único archivo, como en este caso, desde la interfaz web de Github podés darle al ✎ que aparece cuando estás viendo el archivo, y desde ahí podés editarlo. Cuando "commiteás" eso, automáticamente te forkea el proyecto, commitea el cambio en un branch nuevo, y crea el pull request 🎉

¡Un abrazo!
