### ISSUE TITLE
consistency.sh

### ISSUE THREAD

**Issue by tomas-schmidt** [sisoputnfrba/osada-tests#2]
Hola, probando el consistency.sh encontré un issue. A veces el numero en la variable $$ que genera hace que el archivo se exceda en la cantidad de caracteres que puede tener de nombre, y no se puede crear.

Saludos

**Comment by mgarciaisaia** [comment]
Recién veo esto. Gracias por el reporte, ¡che!

Lo fixeé hace unos días en fd2ac846cc1afa4f0356960e7a86e01ac9a8eaa0. En 32 bits, [el máximo PID que puede haber es 32k](http://unix.stackexchange.com/a/16884/49371), así que tudo bom, tudo legal 👌👌
